Models/BlackBoard.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AftebiClassroom.Models
{
    public class BlackBoard
    {
        public int Id { get; set; }
        public int ClassroomId { get; set; }
        public string AppUserId { get; set; }
        public ClassroomUser ClassroomUser { get; set; } 
        public string content { get; set; } 
        public string FilesPaths { get; set; }
    }
}

Models/Classroom.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AftebiClassroom.Models
{
    public class Classroom
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string title { get; set; }
        public string description { get; set; }
        public DateTime time_created { get; set; }
        public string AppUserID { get; set; }
        public AppUser AppUser { get; set; }
        public ICollection<ClassroomUser> ClassroomUsers { get; set; }
    }
}

ViewModels/BlackBoardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace AftebiClassroom.ViewModels
{
    public class BlackBoardViewModel
    {
        public string ClassId { get; set; }
        public string content { get; set; }
        public IFormFileCollection Files { get; set; }
    }
}

ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AftebiClassroom.Models;
namespace AftebiClassroom.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Invite> Invites { get; set; }
        public IEnumerable<ClassroomUser> UserClassrooms { get; set; }
    }
}

ViewModels/SubmitAssignmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
namespace AftebiClassroom.ViewModels
{
    public class SubmitAssignmentViewModel
    {
        public string AssignmentID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public IFormFileCollection Files { get; set; }
    }
}

Controllers/ClassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using AftebiClassroom.Models;
using AftebiClassroom.Models.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Web;
using System.IO;
using AftebiClassroom.ViewModels;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using MailKit.Net.Smtp;
using MimeKit;
namespace AftebiClassroom.Controllers
{
    public class ClassroomController : Controller
    {
        private readonly IClassroomRepository _classRepo;
        private readonly IClassroomUserRepository _classUserRepo;
        private readonly IBlackBoardRepository _boardRepo;
        private readonly IInviteRepository _inviteRepo;
        private readonly IAssignmentRepository _assignmentRepo;
        private readonly ISubmittedAssignmentRepository _submittedAssignmentRepo;
        private readonly ICommentRepository _commentRepo;
        // private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
       // private readonly System.Web.Mvc.HtmlHelper _htmlHelper;
        public ClassroomController(IClassroomRepository classRepo,IClassroomUserRepository classUser, 
            IBlackBoardRepository boardRepo, IInviteRepository inviteRepo, IAssignmentRepository assignmentRepo, 
            ISubmittedAssignmentRepository submittedAssignmentRepo,
            ICommentRepository commentRepo,
            IWebHostEnvironment hostingEnvironment, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _classRepo = classRepo;
            _classUserRepo = classUser;
            _boardRepo = boardRepo;
            _inviteRepo = inviteRepo;
            _assignmentRepo = assignmentRepo;
            _submittedAssignmentRepo = submittedAssignmentRepo;
            _commentRepo = commentRepo;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public ViewResult Index()
        {
            if (!(_signInManager.IsSignedIn(User)))
            {
                return View("Views/Home/Privacy.cshtml");
            }
            else
            {
                return View("Views/Home/Privacy.cshtml");
            }

                var model = _classRepo.GetAllClassrooms();

            return View(model);
        }
        public ViewResult Details(int id)
        {
            Classroom Classroom = _classRepo.GetClassroom(id);
            if (Classroom == null)
            {
                Response.StatusCode = 404;
                return View("NotFound"); 
            }
            return View(Classroom);
        }
        [Authorize]

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Classroom model)
        {
            string Id = null;
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                Id = _userManager.GetUserId(HttpContext.User);
            }
            if (ModelState.IsValid)
            {
                Classroom newClass = new Classroom
                {
                    title = model.title,
                    description = model.description,
                    AppUserID = Id,
                    time_created = DateTime.Now
                };
                _classRepo.Add(newClass);

                ClassroomUser newClassUser = new ClassroomUser
                {
                    ClassroomId = newClass.ID,
                    AppUserId = Id,
                    Role = "Mentor"
                };
                _classUserRepo.Add(newClassUser);

                return RedirectToAction("Home", new { id = newClass.ID, loadPartial = "BlackBoard" });
            }
            return View();
        }
        [Authorize]

        [HttpGet]
        public ViewResult Edit(int id)
        {
            Classroom Class = _classRepo.GetClassroom(id);
            Classroom newClass = new Classroom
            {
                ID = Class.ID,
                title = Class.title,
                description = Class.description,
                AppUserID = Class.AppUserID
            };
            return View(newClass);
        }
        [HttpPost]
        public IActionResult Edit(Classroom model)
        {
            if (ModelState.IsValid)
            {
                Classroom Class = _classRepo.GetClassroom(model.ID);
                Class.title = model.title;
                Class.description = model.description;
                Classroom updatedClass = _classRepo.Update(Class);
                return RedirectToAction("Home", new { id = model.ID, loadPartial = "BlackBoard" });
            }
            return View(model);
        }
       [Authorize]

       [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(ClassroomHomeViewModel chvm)
        {
            var Class = _classRepo.GetClassroom(chvm.Classroom.ID);
            _classRepo.Delete(Class.ID);
            return RedirectToAction("Index","Home");
        }
        [HttpGet]
        public IActionResult Home(int id, string loadPartial)
        {
            Classroom Classroom = _classRepo.GetClassroom(id);
            string userId = null;
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                userId = _userManager.GetUserId(HttpContext.User);
            }
            ClassroomUser classUser = _classUserRepo.GetClassroomUser(id, userId);
            if (Classroom == null || classUser == null)
            {
                Response.StatusCode = 404;
                return View("NotFound");
            }
            ClassroomHomeViewModel chvm = new ClassroomHomeViewModel();
            chvm.Classroom = Classroom;
            chvm.BlackBoards = _boardRepo.GetClassBlackBoards(id);
            List<List<Comment>> Comments = new List<List<Comment>>();
            foreach (BlackBoard bb in chvm.BlackBoards)
            {
                Comments.Add(_commentRepo.GetBlackBoardComments(bb.Id).ToList());
            }
            chvm.Comments = Comments;
            chvm.ClassroomUserRole = classUser.Role;
            chvm.ClassroomMentors = _classUserRepo.GetClassroomMentors(id);
            chvm.ClassroomStudents = _classUserRepo.GetClassroomStudents(id);
            chvm.StudentInvites = _inviteRepo.GetAllInvites(id);
            chvm.Assignments = _assignmentRepo.GetClassAssignments(id);
            ViewData["loadPartial"] = loadPartial;
            return View(chvm);
        }
        [HttpGet]
        public IActionResult BlackBoard(int id)
        {
            ViewBag.ClassId = id;
            return View();
        }
        [HttpPost]
        public IActionResult BlackBoard(ClassroomHomeViewModel model)
        {
            string Id = null;
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                Id = _userManager.GetUserId(HttpContext.User);
            }
            if (ModelState.IsValid)
            {
                string filename = null;
                List<string> files = new List<string>();
                if (model.BlackBoardViewModel.Files != null)
                {
                    foreach (IFormFile file in model.BlackBoardViewModel.Files)
                    {
                        string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "blackboard");
                        filename = Guid.NewGuid().ToString() + "_" + file.FileName;
                        files.Add(filename);
                        string filePath = Path.Combine(uploadsFolder, filename);
                        file.CopyTo(new FileStream(filePath, FileMode.Create));
                    }
                }
                BlackBoard newBoard = new BlackBoard
                {
                    ClassroomId = Convert.ToInt32(model.BlackBoardViewModel.ClassId),
                    AppUserId = Id,
                    content = model.BlackBoardViewModel.content,
                    FilesPaths = string.Join(",", files)
                };
                _boardRepo.Add(newBoard);
            }
            return RedirectToAction("Home", new { id = model.BlackBoardViewModel.ClassId, loadPartial = "BlackBoard" });
        }
        public ViewResult BlackBoardIndex()
        {
            var model = _boardRepo.GetAllBlackBoards();
            return View(model);
        }

        public IActionResult DeleteBlackBoard(int id)
        {
            BlackBoard bb = _boardRepo.GetBlackBoard(id);
            if (bb == null)
            {
                return View("NotFound");
            }
            return View("BlackBoardDelete", bb);
        }
        [Authorize]
        [HttpPost, ActionName("DeleteBlackBoard")]
        public IActionResult BlackBoardDeleteConfirmed(int id)
        {
            BlackBoard bb = _boardRepo.GetBlackBoard(id);
            _boardRepo.Delete(bb.Id);
            return RedirectToAction("Home", new { id = bb.ClassroomId, loadPartial = "BlackBoard" });
        }
        [HttpPost]
        public IActionResult InviteStudents(string ClassId, string emails)
        {
            int id = Convert.ToInt32(ClassId);
            Classroom classroom = _classRepo.GetClassroom(id);
            AppUser user = _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User)).Result;
            string[] Emails = emails.Split(" ");
            foreach (string email in Emails)
            {
                //Create invite first
                Invite invite = new Invite
                {

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AftebiClassroom.Models;
using AftebiClassroom.Models.Repositories;
using AftebiClassroom.ViewModels;
using Microsoft.AspNetCore.Identity;
using System.Web;
using Microsoft.AspNetCore.Http;

namespace AftebiClassroom.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IClassroomRepository _classRepo;
        private readonly IInviteRepository _inviteRepo;
        private readonly IClassroomUserRepository _classroomUserRepo;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public HomeController(ILogger<HomeController> logger, IClassroomRepository classRepo, IInviteRepository inviteRepo, IClassroomUserRepository classroomUserRepo, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _logger = logger;
            _classRepo = classRepo;
            _classroomUserRepo = classroomUserRepo;
            _signInManager = signInManager;
            _userManager = userManager;
            _inviteRepo = inviteRepo;
            //this.userID = Convert.ToInt32(_userManager.GetUserId(User));
        }
        public async Task<IActionResult> Index()
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                var id = _userManager.GetUserId(HttpContext.User);
                var user = await _userManager.FindByIdAsync(id);
                if (user != default)
                {
                    string user_email = _userManager.FindByIdAsync(id).Result.Email;
                    HomeViewModel hvm = new HomeViewModel
                    {
                        Invites = _inviteRepo.GetUserInvites(user_email),
                        UserClassrooms = _classroomUserRepo.GetUserClassrooms(id)
                    };
                    return View(hvm);
                }
            }
            else 
            {
                return View("Views/Home/Index.cshtml");
            }

            return View();
        }

        public IActionResult Privacy()
        {
           
                return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Classroom/BlackBoard.cshtml
@model AftebiClassroom.ViewModels.BlackBoardViewModel

@{
    ViewData["Title"] = "BlackBoard";
}

<h1>BlackBoard</h1>

<h4>Black Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="BlackBoard" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="ClassId" type="hidden" value="@ViewBag.ClassId"/>
            <div class="form-group">
                <label asp-for="content" class="control-label"></label>
                <input asp-for="content" class="form-control" />
                <span asp-validation-for="content" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="Files" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="Files" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Classroom/BlackBoardDelete.cshtml
@model AftebiClassroom.Models.BlackBoard

@{
    ViewData["Title"] = "BlackBoardDelete";
}

<h3>Are you sure you want to delete this post?</h3>
<div>
    All the data of this post will be permenantly lost.<br/><br/>
    <form asp-action="DeleteBlackBoard" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Home" asp-route-id="@Model.ClassroomId" asp-route-loadPartial="BlackBoard">Cancel</a>
    </form>
</div>

Views/Classroom/Create.cshtml
@model AftebiClassroom.Models.Classroom

@{
    ViewData["Title"] = "Create";
}

<h4>Create Your Own Classroom!</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label">Title</label>
                <input asp-for="title" class="form-control" placeholder="Give your Classroom a name"/>
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label">Description</label>
                <textarea asp-for="description" class="form-control" rows="5" cols="30" 
                          placeholder="Enter some description for your classroom"></textarea>
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Let the learning Commence!" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Cancel</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Classroom/DeleteAssignment.cshtml
@model AftebiClassroom.Models.Assignment

<h3>Are you sure you want to delete this assignment?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="DeleteAssignment">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Home" asp-route-id="@Model.ClassroomID">Back to Home</a>
    </form>
</div>

Views/Classroom/Details.cshtml
@model AftebiClassroom.Models.Classroom

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Classroom</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.time_created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.time_created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AppUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AppUser.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Classroom/Edit.cshtml
@model AftebiClassroom.Models.Classroom

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit Classroom</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <textarea asp-for="description" class="form-control" rows="5" cols="30"></textarea>
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Home" asp-route-id="@Model.ID" asp-route-loadPartial="BlackBoard">Cancel Edit</a>
</div>

Views/Classroom/Index.cshtml
@model IEnumerable<AftebiClassroom.Models.Classroom>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.time_created)
            </th>
            <th>
                Created By
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time_created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppUser.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Classroom/_AssignmentPartial.cshtml
@model AftebiClassroom.ViewModels.ClassroomHomeViewModel
@inject Microsoft.AspNetCore.Identity.UserManager<AppUser> _userManager
@using AftebiClassroom

<h4>Assignments</h4>
<hr />
@if (Model.ClassroomUserRole == "Mentor")
{
    <div>
        <form enctype="multipart/form-data" asp-action="NewAssignment" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="AssignmentViewModel.ClassId" type="hidden" value="@ViewData["ClassId"]" />
            <div class="form-group">
                <input placeholder="Title of Assignment here" asp-for="AssignmentViewModel.Title" class="form-control"/>
                <span asp-validation-for="AssignmentViewModel.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea placeholder="Enter some description for your assignment" asp-for="AssignmentViewModel.Description" class="form-control" rows="5" cols="30"></textarea>
                <span asp-validation-for="AssignmentViewModel.Description" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Upload Files:</label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="AssignmentViewModel.Files" class="form-control custom-file-input" multiple>
                        <label class="custom-file-label">Choose Files...</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Post Assignment" class="btn btn-primary" />
            </div>
            <script>
                $(document).ready(function () {
                    $('.custom-file input').change(function (e) {
                        var files = [];
                        for (var i = 0; i < $(this)[0].files.length; i++) {
                            files.push($(this)[0].files[i].name);
                        }
                        $(this).next('.custom-file-label').html(files.join(', '));
                    });
                });
            </script>
        </form>
    </div>
}
<div>
    @foreach (var item in Model.Assignments)
    {
        AppUser user = await _userManager.FindByIdAsync(item.AppUserID);
    <div class="content-block">
        <h5>@item.Title</h5>
        <h6>@user</h6>
        <hr />
        @CustomHelpers.DisplayWithLinksFor(item.Description)
        @if (item.Files != null)
        {
            string[] files = item.Files.Split(",");
            if (files.Count() >1 || (files.Count() ==1 && files[0].Length != 0))
            {
                <hr/>
            }
            foreach (string file in files)
            {
                if (file.Length == 0)
                {
                    continue;
                }
                var filePath = "~/posted_assignments/" + file;
                var filename = file.Substring(file.IndexOf("_") + 1, file.Length - file.IndexOf("_") - 1);
                var fileUrl = "https://localhost:5001" + "/posted_assignments/" + file;
                <a target="_blank" href="@fileUrl">
                    @filename
                </a>
                <br />
            }
        }
        <hr/>
        @if (Model.ClassroomUserRole == "Mentor")
        {
            <a class="text-primary" asp-action="ViewSubmissions" asp-route-id="@item.ID">View Submissions</a><br />
            <a class="text-danger" asp-controller="Classroom" asp-action="DeleteAssignment" asp-route-id="@item.ID">Delete this Assignment</a>
        }
        else
        {
            <a class="text-primary" asp-action="SubmitAssignment" asp-route-id="@item.ID">Submit Assignment</a><br />
            <a class="text-primary" asp-action="ViewSubmissions" asp-route-id="@item.ID">View Your Submissions</a><br />
        }

    </div>
    <br/>
    }

</div>
<style>
    .content-block {
        border: 1px solid #dddddd;
        border-radius: 20px;
        padding: 20px;
    }
</style>

Views/Classroom/_BlackBoardIndexPartial.cshtml
@model AftebiClassroom.ViewModels.ClassroomHomeViewModel
@inject Microsoft.AspNetCore.Identity.UserManager<AppUser> _userManager
@using AftebiClassroom

<h4>Black Board</h4>
<hr />
<div>
    <form enctype="multipart/form-data" asp-action="BlackBoard" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="BlackBoardViewModel.ClassId" type="hidden" value="@ViewData["ClassId"]" />
        <div class="form-group">
            <textarea placeholder="Share something with the class!" asp-for="BlackBoardViewModel.content" class="form-control" rows="5" cols="30"></textarea>
            <span asp-validation-for="BlackBoardViewModel.content" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Upload Files:</label>
            <div class="col-sm-10">
                <div class="custom-file">
                    <input asp-for="BlackBoardViewModel.Files" class="form-control custom-file-input" multiple>
                    <label class="custom-file-label">Choose Files...</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Post" class="btn btn-primary" />
        </div>
        <script>
            $(document).ready(function () {
                $('.custom-file input').change(function (e) {
                    var files = [];
                    for (var i = 0; i < $(this)[0].files.length; i++) {
                        files.push($(this)[0].files[i].name);
                    }
                    $(this).next('.custom-file-label').html(files.join(', '));
                });
            });
        </script>

    </form>
</div>

<div>
    @{ 
        int index = -1;
    } 
    @foreach (var item in Model.BlackBoards)
    {
        index += 1;
        AppUser user = await _userManager.FindByIdAsync(item.AppUserId);
    <div class="content-block">
        <h6>@user</h6>
        <hr />
        @CustomHelpers.DisplayWithLinksFor(item.content)
        @if (item.FilesPaths != null)
        {
            string[] files = item.FilesPaths.Split(",");
            if (files.Count() > 1 || (files.Count() == 1 && files[0].Length != 0))
            {
                <hr />
            }
            foreach (string file in files)
            {
                if (file.Length == 0)
                {
                    continue;
                }
                var filePath = "~/blackboard/" + file;
                var filename = file.Substring(file.IndexOf("_") + 1, file.Length - file.IndexOf("_") - 1);
                var fileUrl = "https://localhost:5001" + "/blackboard/" + file;
                <a target="_blank" href="@fileUrl">
                    @filename
                </a>
                <br />
            }
        }
        @if (Model.ClassroomUserRole == "Mentor")
        {
            <hr/>
            <a class="text-danger" asp-controller="Classroom" asp-action="DeleteBlackBoard" asp-route-id="@item.Id">Delete this Post</a>
        }
        <hr/>
        <div style="background-color: #eeeeee;padding:20px;height:100%;width:100%;border-bottom-left-radius:inherit;border-bottom-right-radius:inherit">
            <form class="form-inline" asp-action="AddComment" method="post">
                <input type="hidden" asp-for="@Model.Comment.BlackBoardId" value="@item.Id" />
                <input style="width:750px" type="text" class="form-control" asp-for="@Model.Comment.Content" placeholder="Comment on this Post..." />
                <input type="submit" value="Submit" class="btn btn-light" />
            </form>
            @foreach (Comment comment in Model.Comments[index])
            { 
                <hr/>
                <span><b>@comment.AppUser.UserName</b>&nbsp;&nbsp;@comment.TimeCreated.Date.ToLongDateString()</span><br/><br/>
                <p>@comment.Content</p>
                @if (Model.ClassroomUserRole == "Mentor")
                {
                    <a class="text-danger" href="#">Delete</a>
                }
            }
        </div>
    </div>
        <br/>
    }

</div>
<style>
    .content-block {
        border: 1px solid #dddddd;
        border-radius: 20px;
        padding: 20px;
    }
</style>